spring.application.name=SB-Redis-App

#Redis Server
spring.data.redis.host=gold-quiet-cap-97975.db.redis.io
spring.data.redis.port=10664
spring.data.redis.username=default
spring.data.redis.password=sykHKKcz8jIoybUP21lQKZzpkw0YySrD
