spring.application.name=02-Customer_API

#DataSource properties
spring.datasource.url=jdbc:mysql://localhost:3306/ashokit_ecomm
spring.datasource.username=root
spring.datasource.password=root

#ORM-JPA Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SMTP Mail Config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=chavanpradip1995@gmail.com
spring.mail.password=ejih xxrw ksjz gikm

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#Spring-Security
#spring.security.user.name=admin
#spring.security.user.password=admin@123